apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-user
spec:
  replicas: 1
  selector:
    matchLabels: 
      backend: user
  template: 
    metadata:
      labels:
        backend: user
    spec:
      containers:
        - name: backend-user
          image: kalax1011/backend-user
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata: 
  name: service-user
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector: 
    backend: user